# 要处理的视频父路径
inputFolder: 'data/'
outputFolder: 'results/'
# 视频降帧参数
downFrameRateStage:
  BinaryFileProcess:
    downRate: [1, 0.5, 0.25]
    h: 2160 #输入YUV视频帧高度
    w: 3840 #输入YUV视频帧宽度

# 视频绛分辨率参数
downResolutionStage: 
  FFmpeg:
    downRate: [1, 0.5, 0.25]
    h: 2160 #输入YUV视频帧高度
    w: 3840 #输入YUV视频帧宽度

# encodingStage:
#   HEVC:
#     Q: [20, 25, 30, 35, 40, 45]
#   VVC:
#     Q: [20, 25, 30, 35, 40, 45]
#   HLVC:
#     param: [1, 2, 3, 4, 5, 6] 

